In [1]:
import numpy as np

rng = np.random.default_rng(seed = 1)

z = rng.normal(size = (3,3))

print(f'Z Shape: {z.shape}\n')
print(f"Z: \n \n {z}")

ModuleNotFoundError: No module named 'numpy'

### Sigmoid

[Reference](README.md#σ)

In [ ]:
σ = 1 / (1 + np.exp(-z))

print(f'σ shape: {σ.shape}')
print(f"σ: \n \n {σ}")

σ shape: (3, 3)
σ: 
 
 [[0.58554635 0.69457972 0.58186572]
 [0.21363414 0.71204889 0.60977691]
 [0.36889662 0.64132464 0.59014683]]


### Softmax

[Reference](README.md/#softmax)

In [ ]:
# Assuming axis 0 is the axis containing the number of classes

a = np.exp(z) / (np.sum(np.exp(z), axis = 0, keepdims=True))

print(f"A shape: {a.shape}")
print(f"A: \n \n {a}")

A shape: (3, 3)
A: 
 
 [[0.62265588 0.34799818 0.31669118]
 [0.1197316  0.37839361 0.35562066]
 [0.25761252 0.27360821 0.32768816]]


### TanH

[Reference](README.md#TanH)

In [ ]:
a = (np.exp(z) - np.exp(-z)) / (np.exp(z) + np.exp(-z))

print(f"A shape: {a.shape}")
print(f"A: \n \n {a}")

A shape: (3, 3)
A: 
 
 [[ 0.33245358  0.67594964  0.31891345]
 [-0.86253373  0.71889574  0.41891435]
 [-0.49067822  0.52347762  0.34923515]]


### ReLU

[Reference](README.md#ReLU)

In [ ]:
a = np.maximum(z, 0)

print(f"A shape: {a.shape}")
print(f"A: \n \n {a}")

A shape: (3, 3)
A: 
 
 [[0.34558419 0.82161814 0.33043708]
 [0.         0.90535587 0.44637457]
 [0.         0.5811181  0.3645724 ]]


### Leaky ReLU

[Reference](README.md#Leaky-ReLU)

In [ ]:
a = np.where(z > 0, z, .01 * z)

print(f"A shape: {a.shape}")
print(f"A: \n \n {a}")

A shape: (3, 3)
A: 
 
 [[ 0.34558419  0.82161814  0.33043708]
 [-0.01303157  0.90535587  0.44637457]
 [-0.00536953  0.5811181   0.3645724 ]]
